// no_07_my_project_cosign_v2_nuxt3/components/_common/ad.vue
<template>
    <div class="ad-component-wrap">
        <div ref="adins"></div>
        <div ref="adpush"></div>
    </div>
</template>

<script lang="ts" setup>
import type { StyleValue } from 'vue/dist/vue.js';


const props_ad = defineProps<{
  adsense: {
    slot: string;
    layout?: string;
    layoutKey?: string;
    format?: string;
    style?: StyleValue;
    widthResponsive?: boolean;
  };
  adfit: {
    src: string;
    unit: string;
    width: string;
    height: string;
  }
}>();


const adsenseClientId = '8783218127052555';
const adins = ref<HTMLDivElement | null>(null);
const adpush = ref<HTMLDivElement | null>(null);

function setAdsenseOption(ins: HTMLElement) {
    if (props_ad.adsense.layout) ins.setAttribute('data-ad-layout', props_ad.adsense.layout);
    if (props_ad.adsense.layoutKey) ins.setAttribute('data-ad-layout-key', props_ad.adsense.layoutKey);
    if (props_ad.adsense.format) ins.setAttribute('data-ad-format', props_ad.adsense.format);
    if (props_ad.adsense.widthResponsive !== undefined) {
        props_ad.adsense.widthResponsive ? ins.setAttribute('data-full-width-responsive', 'true') : ins.setAttribute('data-full-width-responsive', 'false');
    }
    if (props_ad.adsense.style) Object.assign(ins.style, props_ad.adsense.style);
}

function createGoogleAdSense() {
    const ins = document.createElement('ins') as HTMLElement;
    ins.classList.value = "adsbygoogle";
    ins.setAttribute('data-ad-client', `ca-pub-${adsenseClientId}`);
    ins.setAttribute('data-ad-slot', props_ad.adsense.slot);
    setAdsenseOption(ins);
    adins.value?.appendChild(ins);

    const script = document.createElement('script') as HTMLScriptElement;
    script.text = `
        (adsbygoogle = window.adsbygoogle || []).push({});
    `;
    script.async = true;
    adpush.value?.appendChild(script);
}

function createKakaoAdfit() {
    const ins = document.createElement("ins") as HTMLElement;
    ins.classList.value = "kakao_ad_area";
    ins.style.display = "none";
    ins.setAttribute("data-ad-unit", props_ad.adfit.unit);
    ins.setAttribute("data-ad-width", props_ad.adfit.width);
    ins.setAttribute("data-ad-height", props_ad.adfit.height);
    adins.value?.appendChild(ins);

    const script = document.createElement('script') as HTMLScriptElement;
    script.type = 'text/javascript';
    script.src = props_ad.adfit.src;
    script.async = true;
    adpush.value?.appendChild(script);
}



let mutationObserver:MutationObserver | null = null;

onMounted(async () => {

    createGoogleAdSense();
    await nextTick();

    const mutateCallback:MutationCallback = (mutationsList) => {
        let getStatus:string | null = null;

        for (let mutation of mutationsList) {
            
            if (mutation.type !== 'attributes') break;
            if (mutation.attributeName !== 'data-ad-status') break;

            getStatus = adins.value?.children[0].getAttribute('data-ad-status') ?? null;
            

            // filled = 광고가 광고 단위로 반환되어 현재 게재 중입니다
            // unfilled = 반환된 광고가 없으며 광고 단위가 비어 있습니다.
            if (getStatus !== 'filled') {
                Array.from(adins.value!.children).forEach(child => { child.remove(); });
                Array.from(adpush.value!.children).forEach(child => { child.remove(); });
                mutationObserver?.disconnect();
                createKakaoAdfit();
            }
        }
    }

    const options:MutationObserverInit = {
        childList: true,
        subtree: true,
        attributes: true,
        // attributeOldValue: true,
    }
    
    if (adins.value) {
        mutationObserver = new MutationObserver(mutateCallback);
        mutationObserver.observe(adins.value, options);
    }
})

onUnmounted(() => {
    mutationObserver?.disconnect();
})

</script>

// no_09_my_project_hiing_react/src/components/common/ad/Ad.tsx
import React from 'react'


// 애드센스
{/* <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2185824829459089" crossorigin="anonymous"></script> */}


// :adsense="{
//     slot: '9951301238',
//     layoutKey: '-6d+cb-8-4s+o3',
//     format: 'fluid',
//     style: {
//         'display': 'block',
//     }
// }"


const Ad = () => {

    const adins = React.useRef<HTMLDivElement>(null);
    const adpush = React.useRef<HTMLDivElement>(null);

    const adsenseClientId = '2185824829459089';
    const adsenseSlot = '8158915752';
    const adfitUnitId = 'DAN-FMrtqBxqOFeriV7S';

    React.useEffect(() => {

        if (!adins.current || !adpush.current) return;


        function createGoogleAdSense() {
            const ins = document.createElement('ins') as HTMLElement;
            ins.classList.value = "adsbygoogle";
            ins.setAttribute('data-ad-client', `ca-pub-${adsenseClientId}`);
            ins.setAttribute('data-ad-slot', adsenseSlot);
            ins.setAttribute('data-ad-format', 'auto');
            ins.setAttribute('data-full-width-responsive', 'true');
            ins.style.display = 'block';
            adins.current!.append(ins);
          
            const script = document.createElement('script') as HTMLScriptElement;
            script.text = `
              (adsbygoogle = window.adsbygoogle || []).push({});
            `;
            script.async = true;
            adpush.current!.append(script);
        }


        const createKakaoAdfit = () => {
            const ins = document.createElement('ins') as HTMLElement;
            ins.className = 'kakao_ad_area';
            ins.style.display = "none";
            ins.setAttribute('data-ad-unit', adfitUnitId);
            ins.setAttribute('data-ad-width', '320');
            ins.setAttribute('data-ad-height', '50');
            // ins.setAttribute('data-ad-onfail', 'callBackFunc'); // NO-AD시 실행될 Callback 함수명
            adins.current!.append(ins);

            const script = document.createElement('script') as HTMLScriptElement;
            script.async = true;
            script.type = "text/javascript";
            script.src = "//t1.daumcdn.net/kas/static/ba.min.js";
            adpush.current!.append(script);
        }

        // createGoogleAdSense();
        createKakaoAdfit();
    })


    const callBackFunc = React.useCallback((arg: any) => {
        console.log('이게 뭐지', arg)
    }, [])
    
    return (
        <div className='pointer-events-none'>
            <div ref={ adins } className='adins'></div>
            <div ref={ adpush } className='adpush'></div>
        </div>
    )
}

export default Ad;
